// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package wires

import (
	"github.com/hainguyen27798/open-notification/internal/controllers"
	"github.com/hainguyen27798/open-notification/internal/services"
)

// Injectors from mail_wire.go:

func InitMailerController() (*controllers.MailerController, error) {
	iMailService := services.NewMailService()
	mailerController := controllers.NewMailerController(iMailService)
	return mailerController, nil
}
